spring:
  application:
    name: TaskFlow
  datasource:
    url: jdbc:postgresql://localhost:5432/task_flow
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
